services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-datavolume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: jobportal
      MYSQL_ROOT_PASSWORD: jobportal
      MYSQL_PASSWORD: jobportal
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p1234"]
      timeout: 20s
      retries: 10


  springboot-app:
    container_name: jobportal
    image: devanshthakur/jobportal:latest
    restart: on-failure
    build: .
    ports:
      - "80:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: jobportal
      MYSQL_PORT: 3306    # we are in same network so we connect internally.
    depends_on:
      mysqldb:
        condition: service_healthy

volumes:
  mysql-datavolume: